# Variant of the yaml_template_run_pde_solver.yaml
# The original uses "!FilesInFolder", but ideally I would like
# to create slurm scripts without requiring the scattering files
# to already be there...
# So, here we take an alternate approach: pass the chunk size
# information and pre-compute what the files names will be...

---
definitions:
  command: python generate_measurement_files.py
  template: "/home-nfs/oortsang/rlc-repo/data_generation_ood/\
    2025-07-23_base_template_generate_measurement_files.jinja"

  copy_to_item: true

  default_arguments:
    log_dir: logs/gen_data_ood/
    partition: gpu
    num_nodes: 1
    num_gpu: 1
    num_cpu: 4
    exclude_node: ""
    mem: "25G"
    job_walltime: "4:00:00"
    mail_type: end
    mail_user: ""

  submission:
    !SLURMQueue
      jobs_folder: jobs/gen_data_ood
      job_name_key: job_name
      fake_submission: false
      overwrite_scripts: true

  constants:
    scobj_dir: &SCOBJ_DIR "/home-nfs/oortsang/rlc-repo/rlc_data/predictions/\
      2025-09-23_ood_dataset_contrast_2.0/test_scattering_objs"
    sd_mat_dir: &SD_MAT_DIR "/home-nfs/oortsang/rlc-repo/\
      rlc_data/HPS_SD_matrices"
    output_dir: &OUTPUT_DIR "/home-nfs/oortsang/rlc-repo/rlc_data/predictions/\
      2025-09-23_ood_dataset_contrast_2.0"

arguments:
  - !Scalar { name: output_dir, value: *OUTPUT_DIR }
  - !Scalar
    name: scobj_dir,
    value: *SCOBJ_DIR
    metadata_rules: [ !SaveValueInMetadata {path: scobj_dir}]
  - !Scalar { name: sd_mat_dir, value: *SD_MAT_DIR }

  - !Scalar { name: solver_type, value: ls, prefix: "--solver_type" }
  - !Scalar { name: hps_l, value: 4, prefix: "--hps_l" }
  - !Scalar { name: hps_p, value: 16, prefix: "--hps_p" }
  - !Scalar
      name: hps_comp_domain_factor
      value: 2
      prefix: "--hps_comp_domain_factor"

  - !Scalar { name: batch_size, value: 100, prefix: "--batch_size" }
  - !Scalar { name: receiver_radius, value: 100, prefix: "--receiver_radius" }
  - !Scalar { name: start_idx, value: "0", prefix: "--start_idx" }
  - !Scalar { name: create_n_samples, value: -1, prefix: "--create_n_samples" }
  - !Scalar { name: write_every_n, value: 10, prefix: "--write_every_n" }
  - !Scalar { name: debug, value: "--debug", prefix: "" }
  - !Scalar { name: wandb_entity,  value: "recursive-linearization", prefix: "--wandb_entity" }
  - !Scalar { name: wandb_project, value: "2025-07-23_gen_data_low_constrast", prefix: "--wandb_project" }
  - !Scalar { name: wandb_mode, value: "online", prefix: "--wandb_mode" }

  - !Scalar { name: rtol, value: "0.0001", prefix: "--rtol" }
  - !Scalar { name: linsys_solver, value: "bicgstab", prefix: "--linsys_solver" }
  - !Scalar { name: use_half_grid, value: "true", prefix: "--use_half_grid" }
  - !Scalar { name: half_grid_tol_ratio, value: 0.5, prefix: "--half_grid_tol_ratio" }
  - !Scalar { name: max_iter, value: 1000000, prefix: "--max_iter" }
  - !Scalar { name: restart, value: 1000, prefix: "--restart" }
  - !Scalar { name: bicgstab_restart, value: 1000, prefix: "--bicgstab_restart" }

  - !Range
    name: nu_source_freq
    values: [ 1,2,"2.5",3,4,5,6,7,8,9,10 ] # keep as strings to have good control over decimal points later
    prefix: "--nu_source_freq"
    metadata_rules: [ !SaveValueInMetadata { path: nu_sf }]

  - !Range
    name: chunk_start_idx
    start: 0
    end:  1000
    step: 250
    metadata_rules: [ !SaveValueInMetadata {path: input_label}]

  - !ArgumentFromMetadata
    name: input_fp
    format_rule: "{scobj_dir}/scattering_objs_{input_label}.h5"
    sources: [
      {path: scobj_dir, destination: scobj_dir},
      {path: input_label, destination: input_label},
    ]

  # - !FilesInFolder
  #   name: input_fp
  #   folder: *SCOBJ_DIR
  #   regexp_filter: "scattering_objs_([0-9]+).h5"
  #   metadata_rules:
  #     - !ExtractFromFileNameRegexpMetadata
  #       paths: [ input_label ]

  - !ArgumentFromMetadata
    name: job_name
    format_rule: "2025-09-23_ood_dataset_contrast_2.0_measurements_nu_{nu_sf}_meas_{input_label}"
    sources: [
      {path: input_label, destination: input_label},
      {path: nu_sf, destination: nu_sf},
    ]
    metadata_rules: [ !SaveValueInMetadata { path: job_name } ]

  - !ArgumentFromMetadata
    name: output_fp
    prepend: *OUTPUT_DIR
    # prefix: "--output_fp"
    format_rule: "test_measurements_nu_{nu_sf}/measurements_{input_label}.h5"
    sources: [
      {path: job_name, destination: job_name},
      {path: input_label, destination: input_label},
      {path: nu_sf, destination: nu_sf}
    ]