# Have the mapping to fill in for 2025-07-23_yaml_template_generate_measurement_files.yaml
template-file: data_generation_ood/2025-07-23_yaml_template_generate_measurement_files.yaml
templates-rel-dir: data_generation_ood
out-file:      data_generation_ood/2025-09-23_config_generate_test_measurement_files_contrast_2.0.yaml

# Make sure to check these!
run-date: 2025-09-23
nu-sf: '1,2,"2.5",3,4,5,6,7,8,9,10'

wandb-project: "2025-07-23_gen_data_low_constrast"

# General info
rlc-repo: /home-nfs/oortsang/rlc-repo
predictions-rel-dir: rlc_data/predictions
dset: test
input-scobj-dir: 2025-09-23_ood_dataset_contrast_2.0
output-meas-dir: 2025-09-23_ood_dataset_contrast_2.0

# Slurm/badger stuff
logs-rel-dir: logs/gen_data_ood/
partition: "gpu"
jobs-rel-dir: jobs/gen_data_ood
badger-fake-submission: false
badger-overwrite-scripts: true

# File settings
num-samples: 1000
samples-per-chunk: 250
write-every-n: 10

job-name-format: "2025-09-23_ood_dataset_contrast_2.0_measurements_nu_{nu_sf}_meas_{input_label}"

# Solver settings
rho-max: 0.575
solver-type: ls # hps
rtol: 1e-4
linsys-solver: bicgstab
use-half-grid: "true"
half-grid-tol-ratio: 0.5
max-iter: 1000000
bicgstab-restart: 1000
restart: 1000 # this is meant for gmres

# hps-l: 4
# hps-p: 16
# hps-comp-domain-factor: 1
