---
definitions:
  command: python generate_scattering_files.py
  template: 2025-07-23_template_generate_scattering_files.jinja

  copy_to_item: true

  default_arguments:
    mem: "50G"
    logs_folder: logs/gen_data_ood
    # Adjust for the TTIC beehive cluster
    partition: "gpu"
    num_nodes: 1
    num_gpu: 1
    num_cpu: 4
    exclude_node: ""

  submission:
    !SLURMQueue
      jobs_folder: jobs/gen_data_ood
      job_name_key: job_name
      fake_submission: false
      overwrite_scripts: true

  constants:
    dir_out: &DIR_OUT "/home-nfs/oortsang/rlc-repo/rlc_data/predictions/2025-09-23_ood_dataset_contrast_3.0/test_scattering_objs"

arguments:
  - !Scalar { name: n_samples, value: 250, prefix: "--n_samples" }
  - !Scalar { name: n_pixels, value: 192, prefix: "--n_pixels" }
  - !Scalar { name: contrast, value: 3.0, prefix: "--contrast" }
  - !Scalar { name: background_max_radius, value: 0.4, prefix: "--background_max_freq" }
  - !Scalar { name: background_max_freq, value: 4.0, prefix: "--background_max_freq" }
  - !Scalar { name: spatial_domain_max, value: 0.5, prefix: "--spatial_domain_max" }
  - !Scalar { name: gaussian_lpf_param, value: 16.0, prefix: "--gaussian_lpf_param" }
  - !Scalar { name: rho_max, value: 0.575, prefix: "--rho_max" }
  - !Scalar { name: wandb_entity, value: "recursive-linearization", prefix: "--wandb_entity" }
  - !Scalar { name: wandb_project, value: "2025-07-23_gen_data_low_constrast", prefix: "--wandb_project" }
  - !Scalar { name: wandb_mode, value: "online", prefix: "--wandb_mode" }

  - !Range
    name: seed_a
    start: 0
    end: 1_000
    step: 250
    # prefix: "--seed"
    metadata_rules: [ !SaveValueInMetadata { path: seed_a } ]

  - !ArgumentFromMetadata
    name: seed
    prefix: "--seed"
    format_rule: "{seed_a}+3221"
    # + 532 # original seed offset
    sources: [ {path: seed_a, destination: seed_a}]

  - !ArgumentFromMetadata
    name: job_name
    format_rule: "2025-09-23_ood_dataset_contrast_3.0_scattering_objs_{seed_a}"
    sources: [ {path: seed_a, destination: seed_a} ]
    metadata_rules: [ !SaveValueInMetadata { path: job_name } ]

  - !ArgumentFromMetadata
    name: output_fp
    # format_rule: "{job_name}.h5"
    format_rule: "scattering_objs_{seed_a}.h5"
    prepend: *DIR_OUT
    prefix: "--output_fp"
    sources: [ {path: job_name, destination: job_name, path: seed_a, destination: seed_a} ]
